# Use a base image with Python and Flask
FROM python:3.8

# Set the working directory
WORKDIR /app

# Copy the source code into the container
COPY WebPage /app/

# Source the environment script
RUN echo "source /app/set-env-docker.sh" >> /etc/bash.bashrc

# Install Flask and other dependencies
RUN pip install Flask zeep

# Set the entry point to run the Flask application
CMD ["flask", "run", "--host=0.0.0.0", "--port=8081"]
