version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - ./DataBase/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ''
    ports:
      - "8080:80"
    depends_on:
      - mysql

  filtering:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"

  booking:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8182:8182"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - set-env-docker.sh
    ports:
      - "8081:8081"
    depends_on:
      - filtering
      - booking
