openapi: 3.0.1
info:
  description: An API for accessing train information and booking train tickets.
  title: Train API
  version: 1.0.0
servers:
- url: http://localhost:8182/
paths:
  /trains/{departureStation}/{arrivalStation}/{departureDate}/{returnDate}/{numTickets}/{travelClass}:
    get:
      description: Retrieve information about available trains based on specified
        parameters.
      parameters:
      - description: Departure station code
        in: path
        name: departureStation
        required: true
        schema:
          default: stop_area:SNCF:87182113
          type: string
      - description: Arrival station code
        in: path
        name: arrivalStation
        required: true
        schema:
          default: stop_area:SNCF:80359331
          type: string
      - description: Departure date
        in: path
        name: departureDate
        required: true
        schema:
          default: 2024-01-15T00:00:00.000+00:00
          format: date
          type: string
      - description: Return date (optional)
        in: path
        name: returnDate
        required: true
        schema:
          default: 2024-01-16T00:00:00.000+00:00
          format: date
          type: string
      - description: Number of tickets
        in: path
        name: numTickets
        required: true
        schema:
          default: 1
          type: integer
      - description: Travel class
        in: path
        name: travelClass
        required: true
        schema:
          default: Second Class
          type: string
      responses:
        "200":
          content: {}
          description: Successful response
        "400":
          content: {}
          description: Bad request
        "404":
          content: {}
          description: Resource not found
      summary: Get train information
  /book/{userId}/{trainId}/{travelClass}/{ticketType}:
    post:
      description: Book a train based on specified parameters.
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        schema:
          type: string
      - description: Train ID
        in: path
        name: trainId
        required: true
        schema:
          type: string
      - description: Travel class
        in: path
        name: travelClass
        required: true
        schema:
          type: string
      - description: Ticket type
        in: path
        name: ticketType
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: Successful response
        "400":
          content: {}
          description: Bad request
        "404":
          content: {}
          description: Resource not found
      summary: Book a train
  /getBook/{userId}:
    get:
      description: Retrieve book information for a user based on the provided user
        ID.
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: Successful response
        "400":
          content: {}
          description: Bad request
        "404":
          content: {}
          description: Resource not found
      summary: Get book information by user ID
components:
  schemas: {}
x-original-swagger-version: "2.0"
